### ISSUE TITLE
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'

### ISSUE THREAD

**Issue by SavanRajyaguru** [giandifra/arcore_flutter_plugin#137]
Hii, I am creating new flutter AR app . I set `minSdkVersion 24` in build.gradle

> ### I added this in AndroidManifest.xml

```
    <uses-sdk android:minSdkVersion="24"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera.ar" />
```

> ### Add dependencies in build.gradle

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.ar:core:1.8.0'
}
```

### When I run my app its shows me this error:

```
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (245, 38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (246, 13): 'onActivityCreated' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by ss896775** [comment]
it is a Bug in the Plugin. I had the same issue and this worked for me:
https://github.com/giandifra/arcore_flutter_plugin/issues/132

**Comment by alestry-perez** [comment]
I've had the same error, I ended up using a starter template https://github.com/iampawan/FlutterAR, just to get it up and running, and then migrated to embedding v2.

**Comment by JoelNadar-TheSorceror** [comment]
I faced the same issue, And suprisingly once you have everything setup, asin the whole code for the execution including the ARcoreview creation and the node placement, this error vanishes. I updated from version 0.0.10 to 0.0.11 and saw my code running perfectly fine. The ? was present in the library, but it still worked. Not sure why, but you can run into this issue early on.
Perhaps to ensure null safety.

![image](https://user-images.githubusercontent.com/72254442/120286664-225c4c80-c2dc-11eb-9d24-daa466a43733.png)
Just delete the ? at line 246
before: 
`override fun onActivityCreated( activity: Activity?, savedInstanceState: Bundle? )`
after:
`override fun onActivityCreated( activity: Activity, savedInstanceState: Bundle? )`

Another important thing, if you want your app to be AR required. Don't mention it in your app's Android manifest, since it is already written in the plugin's Android Manifest as AR optional.
To change your app to AR required, 
![image](https://user-images.githubusercontent.com/72254442/120287443-e1b10300-c2dc-11eb-8b57-81c4016ab6c3.png)
ensure this is required and not optional, the ar:required isn't needed in your app's android manifest.

**Comment by Sameerkash** [comment]
Getting same, tried everything with no luck 
```
e: /Users/sameerkashyap/Documents/Development/flutter/.pub-cache/git/arcore_flutter_plugin-9e40b879c0941ccdf13124b9cede45ca1625fa69/android/src/main/kotlin/com/difrancescogianmarco/arcore_flutter_plugin/ArCoreView.kt: (245, 38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: /Users/sameerkashyap/Documents/Development/flutter/.pub-cache/git/arcore_flutter_plugin-9e40b879c0941ccdf13124b9cede45ca1625fa69/android/src/main/kotlin/com/difrancescogianmarco/arcore_flutter_plugin/ArCoreView.kt: (246, 13): 'onActivityCreated' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by SavanRajyaguru** [comment]
I also tried everything but doesn't work

**Comment by Sameerkash** [comment]
Fixed it by changing compileSdk and targetSdk from 30 to 29 

Try this @SavanRajyaguru

**Comment by Hamas-ur-Rehman** [comment]
I tried @JoelNadar-TheSorceror method it did fix some errors but doing what @Sameerkash said totally fixes the problem. Thankyou @Sameerkash and @JoelNadar-TheSorceror

**Comment by Pareshoct7** [comment]
> Fixed it by changing compileSdk and targetSdk from 30 to 29
> 
> Try this @SavanRajyaguru

This is the only one solution for this issue

**Comment by Meet-05** [comment]
@Sameerkash  your solution worked , Thanks!

**Comment by asfiul** [comment]
> Fixed it by changing compileSdk and targetSdk from 30 to 29
> 
> Try this @SavanRajyaguru

Thanx . it's work for me
